frameworkVersion: "3"
service: "serverless-offline-local-authorizers-examples-simple"

configValidationMode: warn

plugins:
  - serverless-offline-local-authorizers-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  endpointType: regional

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"

functions:

  publicFunction:
    memorySize: 128
    timeout: 3
    handler: src/TestApi.handleRead
    events:
      - http:
          path: /public
          method: GET

  testFunction:
    memorySize: 128
    timeout: 3
    handler: src/TestApi.handleRead
    events:
      - http:
          path: /allow
          method: GET
          authorizer:
            type: CUSTOM
            authorizerId: "XXX"
          localAuthorizer:
            name: "testAuthFnAllow"
            type: "request"
      - http:
          path: /deny
          method: GET
          authorizer:
            type: CUSTOM
            authorizerId: "XXX"
          localAuthorizer:
            name: "testAuthFnDeny"
            type: "request"
